### ISSUE TITLE
Similar project: Enlarge Your Password!

### ISSUE THREAD

**Issue by eric-brechemier** [josconno/zerostore#1]
Hi @joseph346,

I have developed something similar in JavaScript for use as a Web page:

http://enlargeyourpassword.com/

This definitely works, but not for all websites, as some have Byzantine requirements.

In addition, a difficult problem, each time I subscribe to a new service, is to determine what is the maximum length of passwords supported by the website; many websites still store passwords in plain text, and truncated, at a different length than the one they allow for input in the form to create an account or modify a password. This results in the right password being rejected when compared with the truncated password.

**Comment by emmaconnor** [comment]
Hi @eric-brechemier, thanks for letting me know. Yes, these and other design challenges are something we've been thinking about. Some other issues we've considered:
- How to support changing a user's password on one site only
- How to ensure that a user enters their correct master password when creating a new password
